name: Windows Scheduler
version: v0.0.2
category: Framework
description: Windows scheduler plugin for Rancher.
projectURL: https://github.com/llparse/windows-scheduler
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'windows'
